#!/bin/bash
if [ -z "$1" ]; then
	echo "No system type provided! (laptop, pc)"
  exit 1
fi
set -e
pushd ~/.dotfiles
nvim flake.nix
git diff -U0 *.nix
echo "Rebuilding Nixos..."
sudo nixos-rebuild switch --flake .#$1 &>nixos-switch.log || (cat nixos-switch.log | grep --color error && false)
gen=$(nixos-rebuild list-generations | grep True | grep -o "[0-9]*-[0-9]*-[0-9]* [0-9]*:[0-9]*:[0-9]*  [0-9\.a-zA-Z]*")
git commit -am "$gen"
popd
