#!/bin/bash
if [ -z "$1" ]; then
	echo "No system type provided! (laptop, pc)"
  exit 1
fi
set -e
pushd ~/.dotfiles >> /dev/null
nvim flake.nix
#git diff -U0 -- . ':(exclude)*.log'
echo "Rebuilding Nixos..."
sudo nixos-rebuild switch --flake path:.#$1
home-manager switch --flake path:.
gen=$(nixos-rebuild list-generations | grep True | grep -o "[0-9]*-[0-9]*-[0-9]* [0-9]*:[0-9]*:[0-9]*  [0-9\.a-zA-Z]*")
git add .
git commit -m "$gen"
git pull
git push
popd >> /dev/null
echo "Complete."
